[package]
name = "uu_top"
version = "0.0.1"
edition = "2021"
authors = ["uutils developers"]
license = "MIT"
description = "top ~ (uutils) Display Linux processes"

homepage = "https://github.com/uutils/procps"
repository = "https://github.com/uutils/procps/tree/main/src/uu/top"
keywords = ["acl", "uutils", "cross-platform", "cli", "utility"]
categories = ["command-line-utilities"]

[dependencies]
uucore = { workspace = true, features = ["utmpx"] }
clap = { workspace = true }
libc = { workspace = true }
nix = { workspace = true }
sysinfo = { workspace = true }
chrono = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }

[lib]
path = "src/top.rs"

[[bin]]
name = "top"
path = "src/main.rs"
